name: Proxy Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # jalan tiap 6 jam

jobs:
  scanner:
    runs-on: ubuntu-latest
    concurrency:
      group: proxy-scan

    steps:
      # Checkout repo pakai token bawaan GitHub
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Setup Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      # Pastikan ada package.json (kalau belum ada, buat otomatis)
      - name: Ensure package.json exists
        run: |
          if [ ! -f package.json ]; then
            bun init -y
          fi

      # Install dependencies (kalau ada)
      - name: Install dependencies
        run: bun install

      # Jalankan scanner
      - name: Start Scan
        run: bun run ./helper/proxyip.ts

      # Commit & push hasil scan
      - name: Publish Result
        if: ${{ success() }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update proxyip [skip ci]" || echo "No changes to commit"
          git push origin main
